server:
  port: 9020

spring:
  application:
    name: analytics-service

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: multiservice
    password: 123456
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: '2'

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        default_schema: analytics
        hbm2ddl:
          create_namespaces: true
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        acknowledge-mode: auto